parameters:
  - name: jobName
    type: string

  - name: jobDependsOn
    type: object
    default: []

  - name: dockerContainerRegistry
    type: string

  - name: dockerRepository
    type: string

  - name: dockerPath
    type: string

  - name: dockerTag
    type: string
    default: '$(Build.BuildId)'

  - name: dockerBuildContext
    type: string
    default: "."


jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: ${{ parameters.jobDependsOn }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "##vso[task.setvariable variable=fullImageNameAndTag;isOutput=true]${{ parameters.dockerRepository }}:${{ parameters.dockerTag }}"
        name: setFullImageNameAndTag
        displayName: 'Set fullImageNameAndTag global variable'

      - task: Docker@2
        displayName: 'Login to DockerHub'
        inputs:
          containerRegistry: ${{ parameters.dockerContainerRegistry }}
          command: login

      - task: Docker@2
        displayName: "Build and push image"
        inputs:
          containerRegistry: ${{ parameters.dockerContainerRegistry }}
          command: 'buildAndPush'
          repository: ${{ parameters.dockerRepository }}
          Dockerfile: ${{ parameters.dockerPath }}
          tags: ${{ parameters.dockerTag }}
          buildContext: ${{ parameters.dockerBuildContext }}
