apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-map
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Chart.Name }}
    env: {{ .Values.application.env }}
data:
  ENV: '{{ .Values.application.env }}'
  VERSION: '{{ .Values.application.version }}'
