---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.application.env }}
  labels:
    module: {{ .Chart.Name }}
    env: {{ .Values.application.env }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.service.appPort }}
  selector:
    module: {{ .Chart.Name }}
    env: {{ .Values.application.env }}
  type: ClusterIP
