parameters:
  - name: dockerHubCR
    type: string

  - name: dockerHubRepo
    type: string

  - name: dockerBuildContext
    type: string
    default: '.'

  - name: dockerImageTag
    type: string
    default: $(Build.BuildNumber)

  - name: dockerfilePath
    type: string
    default: 'Dockerfile'

  - name: jobDependsOn
    type: object
    default: []

  - name: jobName
    type: string
    default: 'BuildDockerImage'


jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: ${{ parameters.jobDependsOn }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Login to DockerHub'
        inputs:
          containerRegistry: ${{ parameters.dockerHubCR }}
          command: login

      - task: Docker@2
        displayName: 'Build and push image to DockerHub'
        inputs:
          command: buildAndPush
          repository: ${{ parameters.dockerHubRepo }}
          Dockerfile: ${{ parameters.dockerfilePath }}
          buildContext: ${{ parameters.dockerBuildContext }}
          tags: ${{ parameters.dockerImageTag }}
          containerRegistry: ${{ parameters.dockerHubCR }}


      
