trigger:
  branches:
    include:
      - 'master'
      - 'main'

stages:
  - template: templates/testing-strategy-stages.yaml

  - template: templates/build-docker-image-stages.yaml
    parameters:
      dockerHubCR: TRAZOLA-DOCKER
      dockerHubRepo: trazola/generic_images
      dockerImageTag: python3.11-slim-bullseye
      dockerfilePath: dockerfiles/base.Dockerfile
      stageCondition: |
        and(
          always(),
          in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master')
        )
      
      

