application:
  env: "STAGING"
  version: #{Build.BuildId}#

service:
  servicePort: 8000
  appPort: 8000

hpa:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60

deployment:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  probe:
    scheme: HTTP
    path: /keepalive/k8s
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 20
    timeoutSeconds: 4
    failureThreshold: 4
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 4
    successThreshold: 1
    failureThreshold: 4
  startupProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 4
    failureThreshold: 30
    periodSeconds: 10
